version: '3'
services:
  lms:
    container_name: lms
    restart: always
    image: ghcr.io/hifiberry/extension_lms:8.5.0
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - /data/extensiondata/lms/prefs:/mnt/prefs
      - /data/extensiondata/lms/logs:/mnt/logs
      - /data/library:/library
